### ISSUE TITLE
Provide app configuration based on --env value

### ISSUE THREAD

**Issue by sthzg** [weblogixx/react-webpack-template#1]
As described in this issue https://github.com/newtriks/generator-react-webpack/issues/154#issuecomment-149112001 this feature would allow to import a configuration object based on the current `--env` by using `import config from 'config';`.

The config modules are loaded from:

    src/config/dev.js
    src/config/dist.js
    src/config/test.js

**Comment by sthzg** [comment]
Added an implementation for this feature in f7c211a. To avoid interfering with the `NODE_ENV` variable it sticks `REACT_WEBPACK_ENV` to `process.env` ([here](https://github.com/sthzg/react-webpack-template/blob/f7c211a84d3ace0353ec8bff861f8fde296c222e/webpack.config.js#L18)). Added a test case that checks for the value of `config.appEnv` in `config/test.js`. 

@weblogixx  maybe you could take a short look and check if you think it looks okay.

**Comment by weblogixx** [comment]
@sthzg: Thanks for the work, it is really appreciated. I will have a look at it and give you feedback until the end of the week.

**Comment by weblogixx** [comment]
I just reviewed it and think that this one is really really nice. Thank you for this! If you would adjust the README to reflect the new feature, I will happily merge it. Don`t forget to add yourself to contributors entry :).

**Comment by sthzg** [comment]
Sorry(!) for the noise in the commits. I had troubles rebasing the feature, but the last commit is now correctly squashed to one commit and updated with the current upstream. If the changes to the README are okay I would make it a PR.

**Comment by weblogixx** [comment]
Thats not a problem (I made lots of such "noisy" commits myself). Looks good to me. Looking forward to the PR :+1: :).

**Comment by weblogixx** [comment]
Just merged it. Thanks for the good work :)
