### ISSUE TITLE
Allow port numbers to be overwritten by ENV vars

### ISSUE THREAD

**Issue by sthzg** [weblogixx/react-webpack-template#2]
Sometimes it could  be useful to change the ports of the dev or test servers, e.g. by starting them like

```
SERVER_PORT=<port_number> npm start
SERVER_PORT=<port_number> npm run serve:dist
TEST_SERVER_PORT=<port_number> npm test
```

I will refer a short commit to this issue. If you find the feature worthwhile it might be a way to implement it.

**Comment by weblogixx** [comment]
@sthzg: Thank you, that looks really good to me. Could you please update the README to include this feature? Would be happy to include the pull request for it :)

**Comment by sthzg** [comment]
Great. Just read in the README about the option to run it with a global webpack installation (will check if everything runs as expected that way too). 

One thing I am not sure about are the implications for windows users. AFAIK they can't set env variables like that (further they seem to be fragmented to different shells like powershell, cmd, cygwin). Do you have experience with this topic? Otherwise I have a win 7 and win 10 virtualbox, so I could experiment with it a bit.

**Comment by weblogixx** [comment]
That was the reason I did it with minimist. I can give the environment via command line parameter in this case ("serve": "node server.js --env=dev"). However, this just "emulates" the real node environment. I usually code on a mac too, so you dont have that problem here. However I know that there are problems with some software systems (like react.js reads the node env so it can assume that it should use the dev or live version). 

Will also investigate in this, I got a Win System nearby.

**Comment by sthzg** [comment]
Hm, what do you think about this? It looks promising and as its officially supported should work cross-platform? A quick test of adding an config shows test variables are correctly exposed: 
https://docs.npmjs.com/misc/scripts#configuration

**Comment by weblogixx** [comment]
Basically it seams like a good idea. I will dig into it and look how we could the best results for both plattforms.

**Comment by sthzg** [comment]
Sounds great. For reference I'v added a second commit here to illustrate the later approach e4c0285.

**Comment by sthzg** [comment]
@weblogixx I vote for closing this issue for the time being and possibly renewing it once the new version is stable (I saw that the default port is now in the config, but didn't check whether it's dynamic).

**Comment by weblogixx** [comment]
I think so, too. The new version makes it possible to set the port directly in the config, we could also add it to package.json... Will have to think about this.
