### ISSUE TITLE
PhantomJS fails at travis

### ISSUE THREAD

**Issue by Igonato** [weblogixx/react-webpack-template#26]
@weblogixx Hey there! 

Try restarting the build. A week ago it started to fail for me with "PhantomJS crashed", I had to roll back to an older setup (`karma-phantomjs-launcher@^0.2.1`, `phantomjs` instead of `phantomjs-prebuilt`, etc...). Reverting [this](https://github.com/weblogixx/react-webpack-template/commit/d0720735be73d7910e44c33ca511a84da58b0bb7) basically.

Just wanted to give you a heads up and also maybe you'll have a better idea what causes this.
Note: locally everything works fine. Just travis fails

**Comment by weblogixx** [comment]
Hi @Igonato,

there seems to be a known problem with travis not running well with phantomjs 2, see https://github.com/travis-ci/travis-ci/issues/3225. I will have a look at it when I encounter this error.
