### ISSUE TITLE
in webpack resolve.alias should be resolve.root

### ISSUE THREAD

**Issue by wassname** [weblogixx/react-webpack-template#28]
Here is a suggestion for an improvement to webpack config. Replace resolve.alias with resolve.root.

Why? Alias is bad because it applied to all imports, and in the current state is adds an extra slash breaks some imports. 

E.g. importing 'helpers/actions/ActionWrapper.js' would convert to 'helpers/actions//ActionWrapper.js'

Or am I missing something about the reason it was used?

Instead, add to the search path using [resolve.root.](https://webpack.github.io/docs/configuration.html#resolve-root)

PR submitted.

**Comment by weblogixx** [comment]
Hi @wassname,

I will certainly have a look at it and give it a try. The problem with the double slashes was known, I just did not know the cause of it. Thanks for your support!

**Comment by weblogixx** [comment]
Hi @wassname,

the Idea itself is nice, but I run into errors when trying it out. Seems like we would have to change the way requires are inserted for css and other files. I will try to include this in the next major version of the package (2.0.0), which will include some breaking changes (unit testing via enzyme and other stuff).
