### ISSUE TITLE
Reduce app.js build size by using Webpack's DefinePlugin

### ISSUE THREAD

**Issue by sthzg** [weblogixx/react-webpack-template#4]
Webpack's [DefinePlugin](https://webpack.github.io/docs/list-of-plugins.html#defineplugin) can help reducing output file size by letting the uglifier remove code blocks that are only relevant for non-production builds.

By adding it like this into the `config.plugins` in `cfg/dist.js` the app.js output size drops from 192K to 135K.

```javascript
plugins: [
  new webpack.optimize.DedupePlugin(),
  new webpack.DefinePlugin({
    'process.env': {
      'NODE_ENV': '"production"'
    }
  }),
  new webpack.optimize.UglifyJsPlugin(),
  new webpack.optimize.OccurenceOrderPlugin(),
  new webpack.optimize.AggressiveMergingPlugin(),
  new webpack.NoErrorsPlugin()
]
```

The use is also mentioned in the [React Docs](https://facebook.github.io/react/downloads.html#npm)

> Note: by default, React will be in development mode. To use React in production mode, set the environment variable NODE_ENV to production (using envify or webpack's DefinePlugin). A minifier that performs dead-code elimination such as UglifyJS is recommended to completely remove the extra code present in development mode.

If that's interesting I could provide a PR.

**Comment by weblogixx** [comment]
Seems good, I always wanted to do it the "right" way but didn`t mind to RTFM. Also I had the problem that setting the environment didn`t work correctly when using it with the npm scripts (```NODE_ENV xy npm start``` problematic).

If this is the preferred way, I would be happy to accept. I would provide a new release after the PR for this feature is integrated. Then I will investigate in the other open issue. Sounds reasonable?

**Comment by sthzg** [comment]
:) absolutely, I also think they are not very specific about the solution in the docs (except for mentioning that there is *something*). I also took a peak into https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js and saw that they are also using the `DefinePlugin` for that purpose, so in my opinion it seems to be an accepted solution.

**Comment by weblogixx** [comment]
Perfect, just merged it. The updated version will follow. Thanks again for the good work!
