### ISSUE TITLE
V2 - Releasing new beta build?

### ISSUE THREAD

**Issue by sthzg** [weblogixx/react-webpack-template#42]
@weblogixx could we release a new beta build for the template's 2.x branch, so that the updates to the loader configuration for style files (with/without css modules for all css preprocessors) become available in the V4 branch of the generator?

**Comment by weblogixx** [comment]
Just added the rights for you to publish (at least if you are @sthzg on npm :)). If you are on the 2.x branch, you may just run npm run release:major (or minor or patch). It will always run the following commands:

```
npm version prerelease && git push --follow-tags && npm publish --tag beta
```

**Comment by sthzg** [comment]
😄  Thanks, as it happens I've just pushed my first pre-release in this package. I'd say after https://github.com/newtriks/generator-react-webpack/issues/255 is ready to merge we could go ahead and update the template dependency in the generator's `master`. As far as I can see now, except for the post css support V4 should be quite close to feature completeness then.

**Comment by weblogixx** [comment]
Hi @sthzg,

nice! Hope we will get a fully stable webpack-2 soon.

**Comment by sthzg** [comment]
Hehe, let's see, I've somehow got the feeling that Webpack 2 might still take a bit.
